### ISSUE TITLE
jtlDatabase.dll lässt sich nicht über Add-Type einbinden

### ISSUE THREAD

**Issue by Rogger1990** [GuybrushX/JtlDbWrapper#1]
Die jtlDatabase.dll lässt sich nicht über Add-Type einbinden. Sie habe das falsche Format.
 [System.Reflection.Assembly]::LoadFrom("C:\Program Files (x86)\JTL-Software\jtlDatabase.dll") <- verwenden!!!

**Comment by GuybrushX** [comment]
Hi Rogger,

Liegt wsl. daran, dass du die 64 Bit Version von PowerShell verwendet hast, kann das sein? Also mal die 32 Bit Variante versuchen. Kurzes Feedback wäre nett :-)
